// Decompiled with JetBrains decompiler
// Type: CocoStudio.Model.ViewModel.ViewOrder
// Assembly: CocoStudio.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9A645332-034C-44D3-9062-5E94EDCB75FF
// Assembly location: C:\Program Files (x86)\Cocos\Cocos Studio 2\CocoStudio.Model.dll

namespace CocoStudio.Model.ViewModel
{
  public enum ViewOrder
  {
    Visible = 0,
    FrameVisiable = 1,
    TouchEnable = 2,
    CascadeColor = 3,
    CascadeAlpha = 4,
    PositionType = 5,
    Position = 6,
    AnchorPoint = 7,
    Scale = 8,
    Rotation = 9,
    RotationSkew = 10,
    Alpha = 11,
    Color = 12,
    Zorder = 13,
    Flip = 14,
    SizeType = 15,
    Size = 16,
    Scale9 = 17,
    Panel_ClipEnable = 18,
    ScrollView_InnerSize = 19,
    ScrollView_BounceType = 20,
    ScrollView_DirectionType = 21,
    ListView_AlginTpye = 22,
    Panel_FileData = 23,
    Panel_BackColorType = 24,
    Panel_BackColor = 25,
    Panel_BackAlpha = 26,
    Panel_StartColor = 27,
    Panel_StartAlpha = 28,
    Panel_EndColor = 29,
    Panel_EndAlpha = 30,
    Panel_Vector = 31,
    Text_Animation = 32,
    TextField_StayText = 33,
    Text_String = 34,
    Text_AlignHorizontal = 35,
    Text_AlignVertical = 36,
    Text_FontSize = 37,
    Text_FontFile = 38,
    TextField_PassWord = 39,
    TextField_TextLength = 40,
    Slider_BackImage = 41,
    Slider_BackInnerImage = 42,
    Slider_BackFile = 43,
    Slider_NodeNormal = 44,
    Slider_NodePress = 45,
    Slider_NodeDisable = 46,
    Slider_NodeFile = 47,
    Slider_State = 48,
    Slider_Progress = 49,
    LoadingBar_FileData = 50,
    LoadingBar_Progress = 51,
    LoadingBar_Direction = 52,
    TextAtlas_FileData = 53,
    TextAtlas_Label = 54,
    TextAtlas_StartChar = 55,
    TextAtlas_CharWidth = 56,
    TextAtlas_CharHeight = 57,
    TextAtlas_Text = 58,
    ImageView_FileData = 59,
    CheckBox_BackNormal = 60,
    CheckBox_BackPress = 61,
    CheckBox_BackDisable = 62,
    CheckBox_NodeNormal = 63,
    CheckBox_NodeDisable = 64,
    CheckBox_BackFileData = 65,
    CheckBox_NodeFileData = 66,
    CheckBox_State = 67,
    CheckBox_SelectState = 68,
    Button_Normal = 69,
    Button_Press = 70,
    Button_Disable = 71,
    Button_FileData = 72,
    Button_State = 73,
    Button_Text = 74,
    Button_TextColor = 75,
    Button_FontSize = 76,
    Button_Font = 77,
    Audio_File = 78,
    Audio_Loop = 79,
    Particle_File = 80,
    Map_File = 81,
    FrameData = 100,
    FrameEvent = 101,
  }
}
